#
# Build and test on pull request
#
name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: Build
        run: go build -v ./...
      - name: Build Command
        run: go build -o build/s3web ./cmd/s3web
      - name: Test
        run: go test -v ./...
